# logging.level.guru.springframework=debug
logging:
  level:
    guru.springframework: debug
    # org.springframework: debug
spring:
  # Pretty-print JSON responses
  jackson:
    serialization.INDENT_OUTPUT: true
#  security:
#    user:
#      name: admin
#      password: password
server:
  port: 8443
  ssl:
    # D:\gwt\springgururest\keystore.guru
    key-store: keystore.guru
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat